'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18052
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="skytex")>  _
Partial Public Class LINQSecurityDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Definiciones de métodos de extensibilidad"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.CLPortalUsersDataLink.My.MySettings.Default.skytexConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_qcomtrweb1")>  _
	Public Function sp_qcomtrweb1() As ISingleResult(Of sp_qcomtrweb1Result)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of sp_qcomtrweb1Result))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_accesoweb")>  _
	Public Function sp_accesoweb(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Char(15)")> ByVal rfc As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Char(15)")> ByVal password As String) As ISingleResult(Of sp_accesowebResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), rfc, password)
		Return CType(result.ReturnValue,ISingleResult(Of sp_accesowebResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.sp_datfacweb")>  _
	Public Function sp_datfacweb(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Char(3)")> ByVal ef_cve As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Char(10)")> ByVal tipo_doc As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal num_fol As System.Nullable(Of Integer)) As ISingleResult(Of sp_datfacwebResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), ef_cve, tipo_doc, num_fol)
		Return CType(result.ReturnValue,ISingleResult(Of sp_datfacwebResult))
	End Function
End Class

Partial Public Class sp_qcomtrweb1Result
	
	Private _nom_op As String
	
	Private _prg_cve As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nom_op", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property nom_op() As String
		Get
			Return Me._nom_op
		End Get
		Set
			If (String.Equals(Me._nom_op, value) = false) Then
				Me._nom_op = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prg_cve", DbType:="NVarChar(15) NOT NULL", CanBeNull:=false)>  _
	Public Property prg_cve() As String
		Get
			Return Me._prg_cve
		End Get
		Set
			If (String.Equals(Me._prg_cve, value) = false) Then
				Me._prg_cve = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_accesowebResult
	
	Private _rfc As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rfc", DbType:="NVarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property rfc() As String
		Get
			Return Me._rfc
		End Get
		Set
			If (String.Equals(Me._rfc, value) = false) Then
				Me._rfc = value
			End If
		End Set
	End Property
End Class

Partial Public Class sp_datfacwebResult
	
	Private _ef_cve As String
	
	Private _div_cve As String
	
	Private _cc_tipo As Char
	
	Private _cc_cve As String
	
	Private _alm_cve As String
	
	Private _ven_cve As String
	
	Private _num_fol As Integer
	
	Private _tot_reng As Short
	
	Private _tipo_doc As String
	
	Private _ef_cvep As String
	
	Private _num_folp As System.Nullable(Of Integer)
	
	Private _tipo_docp As String
	
	Private _refer As String
	
	Private _fec_mov As Date
	
	Private _fec_ultact As Date
	
	Private _id_ultact As String
	
	Private _foremb_cve As String
	
	Private _pct_desc As Decimal
	
	Private _tm As String
	
	Private _tc As Decimal
	
	Private _total As Decimal
	
	Private _iva As Decimal
	
	Private _ieps As Decimal
	
	Private _obs As String
	
	Private _pct_canacp As Decimal
	
	Private _fec_prom As Date
	
	Private _sw_facpar As Boolean
	
	Private _sw_entpar As Boolean
	
	Private _forpag_cve As String
	
	Private _fob_cve As String
	
	Private _cf_cve As String
	
	Private _cif_cve As String
	
	Private _dest_cve As String
	
	Private _sw_transp As String
	
	Private _cf_flete As Decimal
	
	Private _cif_flete As Decimal
	
	Private _seguro As Decimal
	
	Private _num_guia As String
	
	Private _contenedor As String
	
	Private _no_bultos As Decimal
	
	Private _tie_trans As Decimal
	
	Private _plazo_pp As Short
	
	Private _pct_descpp As Decimal
	
	Private _sw_impdia As Boolean
	
	Private _sw_consolida As Boolean
	
	Private _dato1 As Decimal
	
	Private _dato2 As Decimal
	
	Private _dato3 As Decimal
	
	Private _dato4 As Decimal
	
	Private _dato5 As Decimal
	
	Private _dato6 As Decimal
	
	Private _dato7 As Decimal
	
	Private _dato8 As Decimal
	
	Private _dato9 As Decimal
	
	Private _dato10 As Decimal
	
	Private _ven_tipo As System.Nullable(Of Char)
	
	Private _foremb_tipo As System.Nullable(Of Char)
	
	Private _plazo As System.Nullable(Of Short)
	
	Private _sw_impexp As Boolean
	
	Private _suc_cve As String
	
	Private _suc_aten As String
	
	Private _imp_letra As String
	
	Private _fec_letra As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ef_cve", DbType:="NChar(3) NOT NULL", CanBeNull:=false)>  _
	Public Property ef_cve() As String
		Get
			Return Me._ef_cve
		End Get
		Set
			If (String.Equals(Me._ef_cve, value) = false) Then
				Me._ef_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_div_cve", DbType:="NChar(3) NOT NULL", CanBeNull:=false)>  _
	Public Property div_cve() As String
		Get
			Return Me._div_cve
		End Get
		Set
			If (String.Equals(Me._div_cve, value) = false) Then
				Me._div_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cc_tipo", DbType:="NChar(1) NOT NULL")>  _
	Public Property cc_tipo() As Char
		Get
			Return Me._cc_tipo
		End Get
		Set
			If ((Me._cc_tipo = value)  _
						= false) Then
				Me._cc_tipo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cc_cve", DbType:="NChar(6) NOT NULL", CanBeNull:=false)>  _
	Public Property cc_cve() As String
		Get
			Return Me._cc_cve
		End Get
		Set
			If (String.Equals(Me._cc_cve, value) = false) Then
				Me._cc_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_alm_cve", DbType:="NChar(3) NOT NULL", CanBeNull:=false)>  _
	Public Property alm_cve() As String
		Get
			Return Me._alm_cve
		End Get
		Set
			If (String.Equals(Me._alm_cve, value) = false) Then
				Me._alm_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ven_cve", DbType:="NChar(6)")>  _
	Public Property ven_cve() As String
		Get
			Return Me._ven_cve
		End Get
		Set
			If (String.Equals(Me._ven_cve, value) = false) Then
				Me._ven_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_num_fol", DbType:="Int NOT NULL")>  _
	Public Property num_fol() As Integer
		Get
			Return Me._num_fol
		End Get
		Set
			If ((Me._num_fol = value)  _
						= false) Then
				Me._num_fol = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tot_reng", DbType:="SmallInt NOT NULL")>  _
	Public Property tot_reng() As Short
		Get
			Return Me._tot_reng
		End Get
		Set
			If ((Me._tot_reng = value)  _
						= false) Then
				Me._tot_reng = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tipo_doc", DbType:="NChar(6) NOT NULL", CanBeNull:=false)>  _
	Public Property tipo_doc() As String
		Get
			Return Me._tipo_doc
		End Get
		Set
			If (String.Equals(Me._tipo_doc, value) = false) Then
				Me._tipo_doc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ef_cvep", DbType:="NChar(3)")>  _
	Public Property ef_cvep() As String
		Get
			Return Me._ef_cvep
		End Get
		Set
			If (String.Equals(Me._ef_cvep, value) = false) Then
				Me._ef_cvep = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_num_folp", DbType:="Int")>  _
	Public Property num_folp() As System.Nullable(Of Integer)
		Get
			Return Me._num_folp
		End Get
		Set
			If (Me._num_folp.Equals(value) = false) Then
				Me._num_folp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tipo_docp", DbType:="NChar(6)")>  _
	Public Property tipo_docp() As String
		Get
			Return Me._tipo_docp
		End Get
		Set
			If (String.Equals(Me._tipo_docp, value) = false) Then
				Me._tipo_docp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_refer", DbType:="NVarChar(20)")>  _
	Public Property refer() As String
		Get
			Return Me._refer
		End Get
		Set
			If (String.Equals(Me._refer, value) = false) Then
				Me._refer = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fec_mov", DbType:="DateTime NOT NULL")>  _
	Public Property fec_mov() As Date
		Get
			Return Me._fec_mov
		End Get
		Set
			If ((Me._fec_mov = value)  _
						= false) Then
				Me._fec_mov = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fec_ultact", DbType:="DateTime NOT NULL")>  _
	Public Property fec_ultact() As Date
		Get
			Return Me._fec_ultact
		End Get
		Set
			If ((Me._fec_ultact = value)  _
						= false) Then
				Me._fec_ultact = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_ultact", DbType:="NChar(3) NOT NULL", CanBeNull:=false)>  _
	Public Property id_ultact() As String
		Get
			Return Me._id_ultact
		End Get
		Set
			If (String.Equals(Me._id_ultact, value) = false) Then
				Me._id_ultact = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_foremb_cve", DbType:="NChar(6)")>  _
	Public Property foremb_cve() As String
		Get
			Return Me._foremb_cve
		End Get
		Set
			If (String.Equals(Me._foremb_cve, value) = false) Then
				Me._foremb_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pct_desc", DbType:="Decimal(0,0) NOT NULL")>  _
	Public Property pct_desc() As Decimal
		Get
			Return Me._pct_desc
		End Get
		Set
			If ((Me._pct_desc = value)  _
						= false) Then
				Me._pct_desc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tm", DbType:="NChar(3)")>  _
	Public Property tm() As String
		Get
			Return Me._tm
		End Get
		Set
			If (String.Equals(Me._tm, value) = false) Then
				Me._tm = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tc", DbType:="Decimal(0,0) NOT NULL")>  _
	Public Property tc() As Decimal
		Get
			Return Me._tc
		End Get
		Set
			If ((Me._tc = value)  _
						= false) Then
				Me._tc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_total", DbType:="Money NOT NULL")>  _
	Public Property total() As Decimal
		Get
			Return Me._total
		End Get
		Set
			If ((Me._total = value)  _
						= false) Then
				Me._total = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_iva", DbType:="Money NOT NULL")>  _
	Public Property iva() As Decimal
		Get
			Return Me._iva
		End Get
		Set
			If ((Me._iva = value)  _
						= false) Then
				Me._iva = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ieps", DbType:="Money NOT NULL")>  _
	Public Property ieps() As Decimal
		Get
			Return Me._ieps
		End Get
		Set
			If ((Me._ieps = value)  _
						= false) Then
				Me._ieps = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_obs", DbType:="NText", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property obs() As String
		Get
			Return Me._obs
		End Get
		Set
			If (String.Equals(Me._obs, value) = false) Then
				Me._obs = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pct_canacp", DbType:="Decimal(0,0) NOT NULL")>  _
	Public Property pct_canacp() As Decimal
		Get
			Return Me._pct_canacp
		End Get
		Set
			If ((Me._pct_canacp = value)  _
						= false) Then
				Me._pct_canacp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fec_prom", DbType:="DateTime NOT NULL")>  _
	Public Property fec_prom() As Date
		Get
			Return Me._fec_prom
		End Get
		Set
			If ((Me._fec_prom = value)  _
						= false) Then
				Me._fec_prom = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sw_facpar", DbType:="Bit NOT NULL")>  _
	Public Property sw_facpar() As Boolean
		Get
			Return Me._sw_facpar
		End Get
		Set
			If ((Me._sw_facpar = value)  _
						= false) Then
				Me._sw_facpar = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sw_entpar", DbType:="Bit NOT NULL")>  _
	Public Property sw_entpar() As Boolean
		Get
			Return Me._sw_entpar
		End Get
		Set
			If ((Me._sw_entpar = value)  _
						= false) Then
				Me._sw_entpar = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_forpag_cve", DbType:="NChar(3)")>  _
	Public Property forpag_cve() As String
		Get
			Return Me._forpag_cve
		End Get
		Set
			If (String.Equals(Me._forpag_cve, value) = false) Then
				Me._forpag_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fob_cve", DbType:="NChar(6)")>  _
	Public Property fob_cve() As String
		Get
			Return Me._fob_cve
		End Get
		Set
			If (String.Equals(Me._fob_cve, value) = false) Then
				Me._fob_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cf_cve", DbType:="NChar(6)")>  _
	Public Property cf_cve() As String
		Get
			Return Me._cf_cve
		End Get
		Set
			If (String.Equals(Me._cf_cve, value) = false) Then
				Me._cf_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cif_cve", DbType:="NChar(6)")>  _
	Public Property cif_cve() As String
		Get
			Return Me._cif_cve
		End Get
		Set
			If (String.Equals(Me._cif_cve, value) = false) Then
				Me._cif_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dest_cve", DbType:="NChar(6)")>  _
	Public Property dest_cve() As String
		Get
			Return Me._dest_cve
		End Get
		Set
			If (String.Equals(Me._dest_cve, value) = false) Then
				Me._dest_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sw_transp", DbType:="NChar(6) NOT NULL", CanBeNull:=false)>  _
	Public Property sw_transp() As String
		Get
			Return Me._sw_transp
		End Get
		Set
			If (String.Equals(Me._sw_transp, value) = false) Then
				Me._sw_transp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cf_flete", DbType:="Money NOT NULL")>  _
	Public Property cf_flete() As Decimal
		Get
			Return Me._cf_flete
		End Get
		Set
			If ((Me._cf_flete = value)  _
						= false) Then
				Me._cf_flete = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cif_flete", DbType:="Money NOT NULL")>  _
	Public Property cif_flete() As Decimal
		Get
			Return Me._cif_flete
		End Get
		Set
			If ((Me._cif_flete = value)  _
						= false) Then
				Me._cif_flete = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_seguro", DbType:="Money NOT NULL")>  _
	Public Property seguro() As Decimal
		Get
			Return Me._seguro
		End Get
		Set
			If ((Me._seguro = value)  _
						= false) Then
				Me._seguro = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_num_guia", DbType:="NVarChar(20)")>  _
	Public Property num_guia() As String
		Get
			Return Me._num_guia
		End Get
		Set
			If (String.Equals(Me._num_guia, value) = false) Then
				Me._num_guia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_contenedor", DbType:="NVarChar(20)")>  _
	Public Property contenedor() As String
		Get
			Return Me._contenedor
		End Get
		Set
			If (String.Equals(Me._contenedor, value) = false) Then
				Me._contenedor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_no_bultos", DbType:="Decimal(0,0) NOT NULL")>  _
	Public Property no_bultos() As Decimal
		Get
			Return Me._no_bultos
		End Get
		Set
			If ((Me._no_bultos = value)  _
						= false) Then
				Me._no_bultos = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tie_trans", DbType:="Decimal(0,0) NOT NULL")>  _
	Public Property tie_trans() As Decimal
		Get
			Return Me._tie_trans
		End Get
		Set
			If ((Me._tie_trans = value)  _
						= false) Then
				Me._tie_trans = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_plazo_pp", DbType:="SmallInt NOT NULL")>  _
	Public Property plazo_pp() As Short
		Get
			Return Me._plazo_pp
		End Get
		Set
			If ((Me._plazo_pp = value)  _
						= false) Then
				Me._plazo_pp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pct_descpp", DbType:="Decimal(0,0) NOT NULL")>  _
	Public Property pct_descpp() As Decimal
		Get
			Return Me._pct_descpp
		End Get
		Set
			If ((Me._pct_descpp = value)  _
						= false) Then
				Me._pct_descpp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sw_impdia", DbType:="Bit NOT NULL")>  _
	Public Property sw_impdia() As Boolean
		Get
			Return Me._sw_impdia
		End Get
		Set
			If ((Me._sw_impdia = value)  _
						= false) Then
				Me._sw_impdia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sw_consolida", DbType:="Bit NOT NULL")>  _
	Public Property sw_consolida() As Boolean
		Get
			Return Me._sw_consolida
		End Get
		Set
			If ((Me._sw_consolida = value)  _
						= false) Then
				Me._sw_consolida = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dato1", DbType:="Money NOT NULL")>  _
	Public Property dato1() As Decimal
		Get
			Return Me._dato1
		End Get
		Set
			If ((Me._dato1 = value)  _
						= false) Then
				Me._dato1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dato2", DbType:="Money NOT NULL")>  _
	Public Property dato2() As Decimal
		Get
			Return Me._dato2
		End Get
		Set
			If ((Me._dato2 = value)  _
						= false) Then
				Me._dato2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dato3", DbType:="Money NOT NULL")>  _
	Public Property dato3() As Decimal
		Get
			Return Me._dato3
		End Get
		Set
			If ((Me._dato3 = value)  _
						= false) Then
				Me._dato3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dato4", DbType:="Money NOT NULL")>  _
	Public Property dato4() As Decimal
		Get
			Return Me._dato4
		End Get
		Set
			If ((Me._dato4 = value)  _
						= false) Then
				Me._dato4 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dato5", DbType:="Money NOT NULL")>  _
	Public Property dato5() As Decimal
		Get
			Return Me._dato5
		End Get
		Set
			If ((Me._dato5 = value)  _
						= false) Then
				Me._dato5 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dato6", DbType:="Money NOT NULL")>  _
	Public Property dato6() As Decimal
		Get
			Return Me._dato6
		End Get
		Set
			If ((Me._dato6 = value)  _
						= false) Then
				Me._dato6 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dato7", DbType:="Money NOT NULL")>  _
	Public Property dato7() As Decimal
		Get
			Return Me._dato7
		End Get
		Set
			If ((Me._dato7 = value)  _
						= false) Then
				Me._dato7 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dato8", DbType:="Money NOT NULL")>  _
	Public Property dato8() As Decimal
		Get
			Return Me._dato8
		End Get
		Set
			If ((Me._dato8 = value)  _
						= false) Then
				Me._dato8 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dato9", DbType:="Money NOT NULL")>  _
	Public Property dato9() As Decimal
		Get
			Return Me._dato9
		End Get
		Set
			If ((Me._dato9 = value)  _
						= false) Then
				Me._dato9 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dato10", DbType:="Money NOT NULL")>  _
	Public Property dato10() As Decimal
		Get
			Return Me._dato10
		End Get
		Set
			If ((Me._dato10 = value)  _
						= false) Then
				Me._dato10 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ven_tipo", DbType:="NChar(1)")>  _
	Public Property ven_tipo() As System.Nullable(Of Char)
		Get
			Return Me._ven_tipo
		End Get
		Set
			If (Me._ven_tipo.Equals(value) = false) Then
				Me._ven_tipo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_foremb_tipo", DbType:="NChar(1)")>  _
	Public Property foremb_tipo() As System.Nullable(Of Char)
		Get
			Return Me._foremb_tipo
		End Get
		Set
			If (Me._foremb_tipo.Equals(value) = false) Then
				Me._foremb_tipo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_plazo", DbType:="SmallInt")>  _
	Public Property plazo() As System.Nullable(Of Short)
		Get
			Return Me._plazo
		End Get
		Set
			If (Me._plazo.Equals(value) = false) Then
				Me._plazo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sw_impexp", DbType:="Bit NOT NULL")>  _
	Public Property sw_impexp() As Boolean
		Get
			Return Me._sw_impexp
		End Get
		Set
			If ((Me._sw_impexp = value)  _
						= false) Then
				Me._sw_impexp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_suc_cve", DbType:="NChar(3)")>  _
	Public Property suc_cve() As String
		Get
			Return Me._suc_cve
		End Get
		Set
			If (String.Equals(Me._suc_cve, value) = false) Then
				Me._suc_cve = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_suc_aten", DbType:="NVarChar(25)")>  _
	Public Property suc_aten() As String
		Get
			Return Me._suc_aten
		End Get
		Set
			If (String.Equals(Me._suc_aten, value) = false) Then
				Me._suc_aten = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_imp_letra", DbType:="NVarChar(255)")>  _
	Public Property imp_letra() As String
		Get
			Return Me._imp_letra
		End Get
		Set
			If (String.Equals(Me._imp_letra, value) = false) Then
				Me._imp_letra = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fec_letra", DbType:="NVarChar(255)")>  _
	Public Property fec_letra() As String
		Get
			Return Me._fec_letra
		End Get
		Set
			If (String.Equals(Me._fec_letra, value) = false) Then
				Me._fec_letra = value
			End If
		End Set
	End Property
End Class
